name: My Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # update to use Node.js 16
      with:
        ref: ${{ github.ref }}
    - name: Setup Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Setup Python
      uses: actions/setup-python@v2 # update to use Node.js 16
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
